### ISSUE TITLE
[RFE] provides json_* functions aliases

### ISSUE THREAD

**Issue by remicollet** [bukka/php-jsond#17]
Here is a proposal to facilitate PHP 5.x usage of this extension (for people using 5.x, before upgrading to 7.x)

- ZEND_MOD_OPTIONAL(json) to ensure json init run before jsond when both available
- check if json_* functions exists, else add aliases

What do you think ? (I can take care of a PR if you think this make sense)

**Comment by bukka** [comment]
There is already a compilation flag `--enable-jsond-with-json-prefix` which should automatically replace json functions if json is running or add a new one if it's not running. Does it work for you?

**Comment by remicollet** [comment]
But this is a **buildtime** option.

I would prefer a **runtime** one (so I can distribute a single binary), which allow jsond to be always there (jsond_* functions) and add aliases (json_*) when possible.

**Comment by remicollet** [comment]
Some discusson about this on https://forum.remirepo.net/viewtopic.php?id=3613

**Comment by remicollet** [comment]
After more thinking, probably don't worth the work... as lot of extension relyig on "json" extension won't work.

**Comment by bukka** [comment]
Ah I see. I think it makes sense but it should be done in optional way. I mean some compilation option that would allow using jsond prefix with json aliases. The reason is that I would like still to have an option to run both extensions which I have been using in my comparison tests in https://github.com/bukka/php-jsond-bench .

I guess it would be actually easier to do what `--enable-jsond-with-json-prefix` and add jsond aliases, constatns and so on. 

Anyway I see it is closed now and I kind of agree that it could break some stuff...
